import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database} from '@/db';
import {allPlaces,initUser,isAdmin,fail,bad,safeText,validOrigin,allowWrite,tooMany} from '@/lib/store';
export const dynamic='force-dynamic';
export async function POST(request:Request){if(!validOrigin(request))return Response.json({error:'请求来源不正确，请刷新后重试。'},{status:403});const user=await getChatGPTUser();if(!user)return Response.json({error:'请先登录后再操作。'},{status:401});try{if(Number(request.headers.get('content-length'))>32768)return bad('内容过长。');if(!await allowWrite(user.userId,'action',60))return tooMany();const parsed=await request.json();if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))return bad("请求格式不正确。");const body=parsed as Record<string,unknown>;await initUser(user);const db=database(),id=crypto.randomUUID(),now=Date.now();const placeId=safeText(body.placeId,100),postId=safeText(body.postId,100);switch(body.action){
case 'profile':{const name=safeText(body.name,32),bio=safeText(body.bio,200);if(!name)return bad('请填写昵称。');await db.prepare('UPDATE profiles SET name=?,bio=? WHERE id=?').bind(name,bio,user.userId).run();break;}
case 'favorite':{if(!(await allPlaces()).some(p=>p.id===placeId))return bad('地点不存在。');if(typeof body.enabled!=='boolean')return bad('操作不正确。');await db.prepare(body.enabled?'INSERT OR IGNORE INTO favorites (user_id,place_id) VALUES (?,?)':'DELETE FROM favorites WHERE user_id=? AND place_id=?').bind(user.userId,placeId).run();break;}
case 'review':{if(!await allowWrite(user.userId,'review',6))return tooMany();if(!(await allPlaces()).some(p=>p.id===placeId))return bad('请选择一个有效地点。');const content=safeText(body.content,3000),rating=Number(body.rating),visitDate=safeText(body.visitDate,10),today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Bangkok'});if(content.length<5)return bad('请写至少 5 个字的体验。');if(!Number.isInteger(rating)||rating<1||rating>5)return bad('请选择 1 至 5 星。');if(!/^\d{4}-\d{2}-\d{2}$/.test(visitDate)||(!Number.isFinite(Date.parse(visitDate))||new Date(visitDate).toISOString().slice(0,10)!==visitDate)||visitDate>today)return bad('请填写有效的购买日期，不能晚于今天。');if(await db.prepare("SELECT id FROM posts WHERE user_id=? AND place_id=? AND visit_date=? AND status='active'").bind(user.userId,placeId,visitDate).first())return bad('你已分享过这家店当天的体验，请勿重复发布。');const photos=Array.isArray(body.photos)?body.photos:[];if(photos.length>3||photos.some((x:unknown)=>typeof x!=='string'))return bad('最多上传 3 张照片。');for(const photo of photos){if(!await db.prepare('SELECT id FROM uploads WHERE id=? AND user_id=?').bind(photo,user.userId).first())return bad('照片不存在或不属于你，请重新上传。');}const price=body.price===''||body.price==null?null:Number(body.price),weight=body.weight===''||body.weight==null?null:Number(body.weight);if(price!==null&&(!Number.isFinite(price)||price<=0||price>1e7)||weight!==null&&(!Number.isFinite(weight)||weight<=0||weight>1e4))return bad('价格与重量应为正数。');const basis=typeof body.basis==='string'&&['整果','净果肉','份','未记录'].includes(body.basis)?body.basis:'未记录';if(price!==null&&basis==='未记录')return bad('填写价格后，请选择整果、净果肉或按份计价。');const insertion=await db.prepare("INSERT INTO posts (id,user_id,place_id,rating,content,visit_date,variety,texture,sweetness,aroma,price,weight,basis,photos,status,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM posts WHERE user_id=? AND place_id=? AND visit_date=? AND status='active')").bind(id,user.userId,placeId,rating,content,visitDate,safeText(body.variety,50)||'未确认',safeText(body.texture,20),safeText(body.sweetness,20),safeText(body.aroma,20),price,weight,basis,JSON.stringify(photos),'active',now,user.userId,placeId,visitDate).run();if(!insertion.meta.changes)return bad('你已分享过这家店当天的体验，请勿重复发布。');break;}
case 'comment':{const content=safeText(body.content,600);if(!content)return bad('请填写评论。');if(!await db.prepare("SELECT id FROM posts WHERE id=? AND status='active'").bind(postId).first())return bad('这条分享已不存在。');await db.prepare('INSERT INTO comments (id,post_id,user_id,content,created_at) VALUES (?,?,?,?,?)').bind(id,postId,user.userId,content,now).run();break;}
case 'like':{if(!await db.prepare("SELECT id FROM posts WHERE id=? AND status='active'").bind(postId).first())return bad('这条分享已不存在。');if(typeof body.enabled!=='boolean')return bad('操作不正确。');await db.prepare(body.enabled?'INSERT OR IGNORE INTO likes (user_id,post_id) VALUES (?,?)':'DELETE FROM likes WHERE user_id=? AND post_id=?').bind(user.userId,postId).run();break;}
case 'deleteReview':{const row=await db.prepare('SELECT user_id FROM posts WHERE id=?').bind(postId).first<{user_id:string}>();if(!row||row.user_id!==user.userId)return Response.json({error:'只能删除自己的分享。'},{status:403});await db.prepare("UPDATE posts SET status='hidden' WHERE id=?").bind(postId).run();break;}
case 'submission':{const kind=body.kind==='correction'?'correction':'new';const old=(await allPlaces()).find(p=>p.id===placeId);if(kind==='correction'&&!old)return bad('地点不存在。');const name=safeText(body.name,100),directions=safeText(body.directions,800);if(!name||!directions)return bad('请填写店名与位置线索。');const lat=Number(body.lat),lng=Number(body.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<13.4||lat>14.2||lng<100.2||lng>101)return bad('请填写曼谷地区的有效经纬度。');const place={id:old?.id||id,name,thai:safeText(body.thai,150),area:safeText(body.area,50)||'曼谷',category:body.category==='榴莲甜品'?'榴莲甜品':'鲜榴莲',lat,lng,directions,description:safeText(body.description,1000)||'由吃货提供的地点线索，营业和供应请出发前确认。',source:old?.source||'',sourceName:old?.sourceName||'社区提供',checked:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Bangkok'}),status:'社区补充 · 库存待确认',varieties:old?.varieties||[]};await db.prepare('INSERT INTO submissions (id,user_id,payload,status,created_at) VALUES (?,?,?,?,?)').bind(id,user.userId,JSON.stringify({kind,placeId:old?.id,place}),'pending',now).run();break;}
case 'report':{const target=safeText(body.target,120),reason=safeText(body.reason,800);if(!reason)return bad('请描述需要处理的问题。');if(!target.startsWith('post:')&&!target.startsWith('place:'))return bad('举报对象不正确。');const exists=target.startsWith('post:')?await db.prepare("SELECT id FROM posts WHERE id=? AND status='active'").bind(target.slice(5)).first():(await allPlaces()).find(p=>p.id===target.slice(6));if(!exists)return bad('举报对象不存在。');await db.prepare('INSERT INTO reports (id,user_id,target,reason,status,created_at) VALUES (?,?,?,?,?,?)').bind(id,user.userId,target,reason,'pending',now).run();break;}
case 'moderate':{if(!await isAdmin(user.userId))return Response.json({error:'没有审核权限。'},{status:403});const target=safeText(body.id,100);if(body.type==='submission'){if(typeof body.status!=='string'||!['approved','rejected'].includes(body.status))return bad('审核状态不正确。');await db.prepare("UPDATE submissions SET status=? WHERE id=? AND status='pending'").bind(body.status,target).run();}else if(body.type==='report'){const report=await db.prepare("SELECT target FROM reports WHERE id=? AND status='pending'").bind(target).first<{target:string}>();if(!report)return bad('举报已处理。');if(body.hide&&report.target.startsWith('post:'))await db.prepare("UPDATE posts SET status='hidden' WHERE id=?").bind(report.target.slice(5)).run();await db.prepare("UPDATE reports SET status='resolved' WHERE id=?").bind(target).run();}else return bad('操作不正确。');break;}
default:return bad('未知操作。');}return Response.json({ok:true,id});}catch(e){return fail(e);}}
