'use client';
import {useEffect,useRef,useState} from 'react';
import type { Map as LeafletMap, LayerGroup, CircleMarker } from 'leaflet';
import type {Place} from '@/lib/places';
export type Bounds={north:number;south:number;east:number;west:number};
export default function DurianMap({places,selected,onSelect,onBounds,location,focus,selectionFocus=0}:{places:Place[];selected:string|null;onSelect:(id:string)=>void;onBounds:(b:Bounds)=>void;location:[number,number]|null;focus:number;selectionFocus?:number}) {
 const el=useRef<HTMLDivElement>(null),map=useRef<LeafletMap|null>(null),markers=useRef<LayerGroup|null>(null),user=useRef<CircleMarker|null>(null); const fitted=useRef(false); const [ready,setReady]=useState(false),[failed,setFailed]=useState(false); const callbacks=useRef({onSelect,onBounds});callbacks.current={onSelect,onBounds};
 useEffect(()=>{let disposed=false;import('leaflet').then(L=>{if(disposed||!el.current)return;const m=L.map(el.current,{zoomControl:false,center:[13.757,100.543],zoom:12});map.current=m;const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(m);let errors=0;tiles.on('tileerror',()=>{errors++;if(errors>4)setFailed(true)});tiles.on('tileload',()=>setFailed(false));L.control.zoom({position:'bottomright'}).addTo(m);markers.current=L.layerGroup().addTo(m);m.on('moveend',()=>{const b=m.getBounds();callbacks.current.onBounds({north:b.getNorth(),south:b.getSouth(),east:b.getEast(),west:b.getWest()})});setReady(true);const o=new ResizeObserver(()=>m.invalidateSize());o.observe(el.current);(m as LeafletMap & {_resizeObserver?:ResizeObserver})._resizeObserver=o;}).catch(()=>setFailed(true));return()=>{disposed=true;(map.current as (LeafletMap & {_resizeObserver?:ResizeObserver})|null)?._resizeObserver?.disconnect();map.current?.remove();map.current=null;};},[]);
 useEffect(()=>{if(!ready)return;let cancelled=false;import('leaflet').then(L=>{if(cancelled||!map.current||!markers.current)return;markers.current.clearLayers();const groups=new Map<string,{p:Place;i:number}[]>();places.forEach((p,i)=>{const key=p.lat+','+p.lng;groups.set(key,[...(groups.get(key)||[]),{p,i}]);});for(const group of groups.values()){const {p,i}=group[0],chosen=group.some(x=>x.p.id===selected),multiple=group.length>1;const icon=L.divIcon({className:'durian-marker-host',html:`<span class="durian-pin ${chosen?'chosen':''} ${multiple?'group':''}"><b>${multiple?group.length+'家':i+1}</b></span>`,iconSize:[40,48],iconAnchor:[20,44]});const marker=L.marker([p.lat,p.lng],{icon,title:multiple?group.length+' 个市场内地点':p.name,alt:p.name}).addTo(markers.current);if(multiple){const popup=document.createElement('div');popup.className='map-group-popup';const title=document.createElement('strong');title.textContent='同一市场内的地点';popup.appendChild(title);group.forEach(x=>{const button=document.createElement('button');button.textContent=(x.i+1)+'. '+x.p.name;button.onclick=()=>{map.current?.closePopup();callbacks.current.onSelect(x.p.id);};popup.appendChild(button);});marker.bindPopup(popup);}else marker.on('click',()=>callbacks.current.onSelect(p.id));}if(!fitted.current&&places.length){map.current.fitBounds(L.latLngBounds(places.map(p=>[p.lat,p.lng] as [number,number])),{padding:[45,55],maxZoom:13});fitted.current=true;}});return()=>{cancelled=true};},[places,selected,ready]);
 useEffect(()=>{if(!ready||!selected)return;const p=places.find(x=>x.id===selected);if(p)map.current?.flyTo([p.lat,p.lng],14,{duration:.7});},[selected,selectionFocus,ready]);
 useEffect(()=>{if(!ready||!location)return;import('leaflet').then(L=>{user.current?.remove();user.current=L.circleMarker(location,{radius:8,color:'#fff',weight:3,fillColor:'#377cea',fillOpacity:1}).addTo(map.current!);map.current?.flyTo(location,14);});},[location,focus,ready]);
 return <><div ref={el} className="map-canvas" aria-label="曼谷榴莲地点地图"/>{failed&&<div className="map-error">地图暂时无法加载，可继续使用地点列表与导航。</div>}</>;
}
