'use client';
import {useState} from 'react';
import {Camera,ExternalLink,MapPin,Play,ArrowUpRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Place} from '@/lib/places';
import {marketPhoto,publicExperiences,shopVideos,tastingGuides} from '@/lib/sourced-content';
export function MarketPhoto(){const [open,setOpen]=useState(false);return <figure className="market-photo"><button onClick={()=>setOpen(true)} aria-label="放大 Or Tor Kor 市场实景照片"><img src={marketPhoto.src} alt="Or Tor Kor 市场摊位上剖开的榴莲，Susan Slater 于 2009 年拍摄" loading="lazy"/><span><Camera size={16}/>市场实景 · 历史照片</span></button><figcaption><a href={marketPhoto.source} target="_blank" rel="noreferrer">Susan Slater · {marketPhoto.date}</a><a href={marketPhoto.license} target="_blank" rel="noreferrer">CC BY-SA 4.0</a><span>原图未修改 · 卡片裁切显示；不是具体商家的当前照片</span></figcaption><Dialog open={open} onOpenChange={setOpen}><DialogContent className="product-dialog photo-dialog"><DialogTitle>Or Tor Kor 市场实景</DialogTitle><DialogDescription>拍摄于 {marketPhoto.date} · Susan Slater · 历史资料</DialogDescription><img src={marketPhoto.src} alt="Or Tor Kor 市场榴莲实景完整照片"/><a className="text-button" href={marketPhoto.source} target="_blank" rel="noreferrer">原图与摄影署名 <ExternalLink size={14}/></a></DialogContent></Dialog></figure>;}
function VideoCard({video}:{video:typeof shopVideos[number]}){const [playing,setPlaying]=useState(false);return <article className="public-video">{playing?<iframe src={'https://www.youtube-nocookie.com/embed/'+video.id} title={video.title} allow="encrypted-media; picture-in-picture; fullscreen" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>:<button className="video-launch" onClick={()=>setPlaying(true)}><span className="play-circle"><Play size={23}/></span><strong>{video.title}</strong><span>播放实地视频 · 点击后连接 YouTube</span></button>}<div className="video-byline"><span>{video.kind} · {video.author}<small>{video.date} 发布 · 历史资料</small></span><a href={'https://www.youtube.com/watch?v='+video.id} target="_blank" rel="noreferrer" aria-label={'在 YouTube 打开'+video.title}><ExternalLink size={17}/></a></div></article>;}
export function PublicExperiences({places,placeId,onPlace}:{places:Place[];placeId?:string;onPlace:(id:string)=>void}){const experiences=publicExperiences.filter(x=>!placeId||x.placeId===placeId);if(!experiences.length)return null;return <section className={'external-experiences '+(!placeId?'external-community':'')}><div className="section-heading"><div><span className="eyebrow">FROM REAL DURIAN JOURNEYS</span><h3>公开探店感受</h3></div><span className="external-badge">外部分享</span></div><p className="external-note">以下为公开原文的中文摘要，保留作者与发布日期。早期资料仅供参考，不计入本站评分。</p><div className="external-grid">{experiences.map(x=><article className="experience-card" key={x.id}><div className="experience-meta"><span>{x.platform}</span><time dateTime={x.date}>{x.date}</time></div><h4>{x.title}</h4><p>{x.summary}</p><div className="experience-author"><span>{x.author}</span><a href={x.url} target="_blank" rel="noreferrer">看原文与照片<ArrowUpRight size={15}/></a></div>{!placeId&&<button className="experience-place" onClick={()=>onPlace(x.placeId)}><MapPin size={14}/>{places.find(p=>p.id===x.placeId)?.name}</button>}</article>)}</div></section>;}
export function ShopMedia({place}:{place:Place}){const videos=shopVideos.filter(v=>v.placeId===place.id),hasPhoto=place.id==='ortorkor';const google='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(place.thai+' '+(place.address||'Bangkok Thailand'));return <section className="shop-media"><div className="section-heading"><h3><Camera size={18}/>照片与实地影像</h3><span className="external-badge">有来源</span></div>{hasPhoto&&<MarketPhoto/>}{videos.map(v=><VideoCard key={v.id} video={v}/>)}{!hasPhoto&&!videos.length&&<p className="external-note">还没有取得可在本站展示的这家店的实景照片。可以查看原平台的照片，也欢迎到店后分享。</p>}<a className="google-photos" href={google} target="_blank" rel="noreferrer">查看 Google 地图上的照片与评价<ExternalLink size={15}/></a><p className="external-note">将打开 Google 地图搜索，请核对店名与分店地址。</p></section>;}
export function TastingGuides({places,onPlace}:{places:Place[];onPlace:(id:string)=>void}){return <section className="tasting-guides"><span className="eyebrow">FIND YOUR NEXT TASTE</span><h2>按你的这一口来找。</h2><p className="external-note">根据已收录资料整理的寻味指南，推荐理由公开可查。</p><div className="guide-grid">{tastingGuides.map(g=><article className="guide-card" key={g.icon}><div className="guide-number">{g.icon}</div><span>{g.subtitle}</span><h3>{g.title}</h3><p>{g.reason}</p><div>{g.placeIds.map(id=><button key={id} onClick={()=>onPlace(id)}>{places.find(p=>p.id===id)?.name}<ArrowUpRight size={15}/></button>)}</div></article>)}</div></section>;}
