'use client';
import {useEffect,useState} from 'react';
import {api,type AppData,type Post,type Comment} from '@/lib/types';
import {PostCard} from './posts';
import {Choice} from './choice';
type Page={posts:Post[];comments:Comment[];likes:AppData['likes'];myLikes:AppData['myLikes'];nextOffset:number|null};
export function ReviewFeed({placeId,postProps}:{placeId:string;postProps:Omit<React.ComponentProps<typeof PostCard>,'post'>}){
 const [query,setQuery]=useState(''),[sort,setSort]=useState('最新体验'),[photos,setPhotos]=useState(false),[rating,setRating]=useState('全部星级'),[retry,setRetry]=useState(0),[page,setPage]=useState<Page|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const url=(offset=0)=>'/api/reviews?'+new URLSearchParams({place:placeId,query,sort:({'最有帮助':'helpful','最高评分':'highest','最低评分':'lowest'} as Record<string,string>)[sort]||'latest',rating:rating==='全部星级'?'0':rating.slice(0,1),photos:photos?'1':'0',offset:String(offset)});
 useEffect(()=>{const controller=new AbortController();setBusy(true);setPage(null);setError('');const timer=setTimeout(()=>{api<Page>(url(),{signal:controller.signal}).then(setPage).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});},250);return()=>{clearTimeout(timer);controller.abort();};},[placeId,query,sort,photos,rating,retry,postProps.data.posts]);
 const more=async()=>{if(page?.nextOffset==null)return;setBusy(true);setError('');try{const next=await api<Page>(url(page.nextOffset));setPage({...next,posts:[...page.posts,...next.posts],comments:[...page.comments,...next.comments],likes:[...page.likes,...next.likes],myLikes:[...page.myLikes,...next.myLikes]});}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <><div className="review-tools"><input aria-label="搜索这家店的体验" placeholder="搜索口感、品种或体验" value={query} onChange={e=>setQuery(e.target.value)}/><div className="navigation-options"><button aria-pressed={photos} className={'chip '+(photos?'active':'')} onClick={()=>setPhotos(!photos)}>只看带图</button><Choice value={sort} onChange={setSort} options={['最新体验','最有帮助','最高评分','最低评分']} label="评价排序"/></div><div className="star-filters" aria-label="按星级筛选评价">{['全部星级','5 星','4 星','3 星','2 星','1 星'].map(r=><button key={r} className={'chip '+(rating===r?'active':'')} aria-pressed={rating===r} onClick={()=>setRating(r)}>{r}</button>)}</div></div>{error&&<p className="form-error" role="alert">{error}<button className="text-button" onClick={()=>setRetry(x=>x+1)}>重试</button></p>}{page?.posts.map(p=><PostCard key={p.id} post={p} {...postProps} data={{...postProps.data,comments:page.comments,likes:page.likes,myLikes:page.myLikes}}/>)}{busy&&<p className="muted">正在读取体验…</p>}{!busy&&page&&!page.posts.length&&<div className="small-empty">没有符合条件的体验。欢迎分享你的真实购买经历。</div>}{page?.nextOffset!=null&&<button className="secondary-button full" disabled={busy} onClick={()=>void more()}>查看更多体验</button>}</>;
}
