export type Place = { id: string; name: string; thai: string; area: string; category: string; lat: number; lng: number; description: string; directions: string; source: string; sourceName: string; checked: string; status: string; varieties: string[]; phone?: string; contact?: string; address?: string; locationPrecision?: string; sourceDate?: string; navigationQuery?: string; };
export const seedPlaces: Place[] = [
 {id:'ortorkor',name:'Or Tor Kor 榴莲市场',thai:'ตลาด อ.ต.ก.',area:'乍都乍',category:'鲜榴莲',lat:13.7973,lng:100.5475,description:'曼谷鲜果市场的榴莲寻味起点。公开探访资料记录了榴莲售卖，具体摊位与当日品种仍需现场确认。',directions:'靠近 MRT Kamphaeng Phet。此标记为市场区域，请到场后寻找榴莲摊位并补充摊号。',source:'https://www.youtube.com/watch?v=7VuMqtUIrE0',sourceName:'市场实地探访 · 2025年5月',checked:'2026-10-06',status:'市场区域 · 摊位待确认',varieties:[]},
 {id:'goldfinger',name:'金手指榴莲摊',thai:'บัวลอยนิ้วทอง เยาวราช',area:'唐人街',category:'鲜榴莲',lat:13.7402,lng:100.5089,description:'公开餐饮资料收录的唐人街榴莲摊，也有榴莲糯米饭。资料中的营业时间存在差异，请出发前确认。',directions:'Yaowarat 路，资料描述靠近 Tang To Kang 金店。坐标仅为附近区域，需核实摊位招牌。',source:'https://www.ryoiireview.com/restaurant/view/2000',sourceName:'Ryoii 店铺资料',checked:'2026-10-06',status:'附近区域 · 位置待核实',varieties:['长柄']},
 {id:'jaepha',navigationQuery:'ทุเรียนเจ้ภา 291 Soi Yaowarat 6 Bangkok',name:'Jae Pha 榴莲摊',thai:'ทุเรียนเจ้ภา เยาวราช',area:'唐人街',category:'鲜榴莲',lat:13.7417,lng:100.5086,description:'Wongnai 收录的 Yaowarat 6 巷榴莲摊。已有资料较旧，营业状态和鲜果供应需要重新确认。',directions:'公开地址：291, Soi Yaowarat 6, Samphanthawong。此为巷口附近标记，请核对招牌。',source:'https://www.wongnai.com/restaurants/630118rS-ทุเรียนเจ้ภา-เยาวราช-ปากซอย6-ตอกเล่งบ๊วยเอี้ย',sourceName:'Wongnai 店铺条目',checked:'2026-10-06',status:'附近区域 · 营业待核实',varieties:[]},
 {id:'durianism-asiatique',name:'Durianism · Asiatique',thai:'Durianism สาขา Asiatique',area:'河畔',category:'榴莲甜品',lat:13.7044,lng:100.5033,description:'品牌官方页面列出的河畔分店线索。榴莲专门品牌，当前菜单、鲜果供应与分店营业情况待核实。',directions:'Asiatique The Riverfront 园区。此标记为园区区域，具体店铺单元待补充。',source:'https://www.nigiwaigroup.co.th/durianism/',sourceName:'Durianism 品牌官网',checked:'2026-10-06',status:'园区区域 · 分店待核实',varieties:[]},
 {id:'durianism-latkrabang',name:'Durianism · Little Walk',thai:'Durianism สาขาลาดกระบัง',area:'拉甲邦',category:'榴莲甜品',lat:13.7213,lng:100.7265,description:'品牌官方页面列出的 Little Walk Lat Krabang 分店线索。适合后续补充探店，现阶段不能确认营业和库存。',directions:'Little Walk Lat Krabang 商业区。此坐标为区域线索，具体入口和店铺位置待核实。',source:'https://www.nigiwaigroup.co.th/durianism/',sourceName:'Durianism 品牌官网',checked:'2026-10-06',status:'附近区域 · 位置待核实',varieties:[]},
{"id": "tatoy", "name": "Ta-Toy 榴莲", "thai": "ทุเรียนตา-ต้อย คนระยอง", "area": "乍都乍", "category": "鲜榴莲", "lat": 13.7973, "lng": 100.5475, "address": "Or Tor Kor Market, Kamphaeng Phet Road, Chatuchak, Bangkok 10900", "directions": "Or Tor Kor 市场，Kamphaeng Phet Road；官方资料提及摊号 7/26、8/30，其他摊号记录有差异。 地图为市场区域线索，不是已核实店门口。", "description": "官方地址线索，摊号需再核对。", "source": "https://page.line.me/aci1662i", "sourceName": "商家 LINE 官方账号", "checked": "2026-10-06", "status": "市场区域 · 营业待核实", "varieties": ["金枕", "长柄"], "phone": "0898186530", "locationPrecision": "市场区域", "sourceDate": "来源未标注更新日期", "contact": "https://page.line.me/aci1662i"},
{"id": "nongnid", "name": "Nong Nid 榴莲", "thai": "ทุเรียนน้องนิด", "area": "乍都乍", "category": "鲜榴莲", "lat": 13.7973, "lng": 100.5475, "address": "Or Tor Kor 市场，Kamphaeng Phet Road, Chatuchak, Bangkok 10900。", "directions": "Or Tor Kor 市场，Kamphaeng Phet Road, Chatuchak, Bangkok 10900。 地图为市场区域线索，不是已核实店门口。", "description": "公开资料列出的市场专卖店，现场摊号待补充。", "source": "https://www.ryoiireview.com/article/durian-delivery", "sourceName": "Ryoii 商店汇编", "checked": "2026-10-06", "status": "市场区域 · 营业待核实", "varieties": [], "phone": "0806096189", "locationPrecision": "市场区域", "sourceDate": "来源未标注更新日期"},
{"id": "rungkan", "name": "Rung Kan 榴莲", "thai": "ทุเรียน เดลิเวอรี่ by รุ่งกาญจน์ อตก.", "area": "乍都乍", "category": "鲜榴莲", "lat": 13.7973, "lng": 100.5475, "address": "Or Tor Kor 市场 6/27 摊位，Chatuchak, Bangkok 10900。", "directions": "Or Tor Kor 市场 6/27 摊位，Chatuchak, Bangkok 10900。 地图为市场区域线索，不是已核实店门口。", "description": "公开资料记录摊号与多品种供应；当日品种请向店铺确认。", "source": "https://www.ryoiireview.com/article/durian-delivery", "sourceName": "Ryoii 商店汇编", "checked": "2026-10-06", "status": "市场区域 · 营业待核实", "varieties": ["金枕", "长柄", "Nok Krachip"], "phone": "0631693224", "locationPrecision": "市场区域", "sourceDate": "来源未标注更新日期"},
{"id": "durianyim", "name": "Durianyim 榴莲微笑", "thai": "ทุเรียนยิ้ม", "area": "汇权", "category": "鲜榴莲", "lat": 13.7784121, "lng": 100.5772338, "address": "773/29 Pracha Rat Bamphen Road, Samsen Nok, Huai Khwang, Bangkok 10310。", "directions": "773/29 Pracha Rat Bamphen Road, Samsen Nok, Huai Khwang, Bangkok 10310。 地图为道路区域线索，不是已核实店门口。", "description": "已有公开店铺地址，地图仅标示道路位置。", "source": "https://www.ryoiireview.com/restaurant/view/12341", "sourceName": "Ryoii 独立店铺资料", "checked": "2026-10-06", "status": "道路区域 · 营业待核实", "varieties": ["金枕"], "phone": "0637585447", "locationPrecision": "道路区域", "sourceDate": "来源未标注更新日期"},
{"id": "nonganda", "name": "Nong Anda 金枕榴莲", "thai": "ทุเรียนหมอนทองน้องอันดา", "area": "汶昆（Bueng Kum）", "category": "鲜榴莲", "lat": 13.7853201, "lng": 100.6686634, "address": "198/26 Soi Golden Neo Lat Phrao–Kaset Nawamin, Khlong Kum, Bangkok 10240。", "directions": "198/26 Soi Golden Neo Lat Phrao–Kaset Nawamin, Khlong Kum, Bangkok 10240。 地图为Khlong Kum 地区中心线索，不是已核实店门口。", "description": "公开地址位于社区巷内，出发前请确认能否到店购买。", "source": "https://www.wongnai.com/restaurants/549789mI-ทุเรียนหมอนทองน้องอันดา", "sourceName": "Wongnai 商家条目", "checked": "2026-10-06", "status": "Khlong Kum 地区中心 · 营业待核实", "varieties": ["金枕"], "phone": "0624254295", "locationPrecision": "Khlong Kum 地区中心", "sourceDate": "来源未标注更新日期"},
{"id": "siamgolden", "name": "Siam Golden Fruit", "thai": "Siam Golden Fruit", "area": "达铃参", "category": "鲜榴莲", "lat": 13.7844802, "lng": 100.4138685, "address": "Soi Borommaratchachonnani 62/4, Bangkok", "directions": "Soi Borommaratchachonnani 62/4；请联系商家确认取货入口。 地图为62 巷道路区域线索，不是已核实店门口。", "description": "资料有巷道线索，具体门牌尚未公开确认。", "source": "https://www.ryoiireview.com/article/durian-delivery", "sourceName": "Ryoii 商店汇编", "checked": "2026-10-06", "status": "62 巷道路区域 · 营业待核实", "varieties": ["金枕", "长柄"], "phone": "0863731262", "locationPrecision": "62 巷道路区域", "sourceDate": "来源未标注更新日期"},
{"id": "naiyut", "name": "Nai Yut 榴莲", "thai": "ทุเรียน นายยุทธ", "area": "拉抛／旺通郎", "category": "鲜榴莲", "lat": 13.7801101, "lng": 100.6111254, "address": "Lat Phrao 94, Phlapphla, Wang Thonglang, Bangkok", "directions": "Lat Phrao 94, Phlapphla, Wang Thonglang, Bangkok；Town in Town 一带。 地图为94 巷道路区域线索，不是已核实店门口。", "description": "多品种专卖店的公开线索，资料没有具体门牌。", "source": "https://www.ryoiireview.com/article/durian-in-thai-shops/", "sourceName": "Ryoii 榴莲店汇编", "checked": "2026-10-06", "status": "94 巷道路区域 · 营业待核实", "varieties": ["金枕", "青尼", "Nok Krachip", "Puang Manee"], "phone": "0819199236", "locationPrecision": "94 巷道路区域", "sourceDate": "来源未标注更新日期"},
{"id": "freshmate", "name": "Fresh Mate 鲜果", "thai": "Fresh Mate", "area": "燕纳瓦（Yan Nawa）", "category": "鲜榴莲", "lat": 13.6957053, "lng": 100.5462155, "address": "99/330 Soi Nonsi 3, Chong Nonsi, Yan Nawa, Bangkok 10120。", "directions": "99/330 Soi Nonsi 3, Chong Nonsi, Yan Nawa, Bangkok 10120。 地图为Chong Nonsi 地区中心线索，不是已核实店门口。", "description": "资料列出鲜榴莲供应；当前供货与到店方式待确认。", "source": "https://www.ryoiireview.com/article/durian-delivery", "sourceName": "Ryoii 商店汇编", "checked": "2026-10-06", "status": "Chong Nonsi 地区中心 · 营业待核实", "varieties": [], "phone": "", "locationPrecision": "Chong Nonsi 地区中心", "sourceDate": "来源未标注更新日期"},
{"id": "adayfresh", "name": "aDay Fresh", "thai": "aDay Fresh", "area": "乍都乍", "category": "鲜榴莲", "lat": 13.8103471, "lng": 100.5711329, "address": "21/7 Wang Dek 1 Building, Floor 1, Room 1C, Vibhavadi Rangsit Road, Chom Phon, Chatuchak, Bangkok 10900。", "directions": "21/7 Wang Dek 1 Building, Floor 1, Room 1C, Vibhavadi Rangsit Road, Chom Phon, Chatuchak, Bangkok 10900。 地图为Chom Phon 地区中心线索，不是已核实店门口。", "description": "果品商家；官方地址与联系方式可查询，榴莲菜单请事先确认。", "source": "https://www.ryoiireview.com/article/durian-delivery", "sourceName": "Ryoii 鲜榴莲供应线索", "checked": "2026-10-06", "status": "Chom Phon 地区中心 · 营业待核实", "varieties": [], "phone": "0925550539", "locationPrecision": "Chom Phon 地区中心", "sourceDate": "来源未标注更新日期", "contact": "https://page.line.me/adayfresh"},
{"id": "prachauthit", "name": "Durian Delivery · Pracha Uthit", "thai": "ทุเรียน Delivery ส่งด่วนใน1ชั่วโมง", "area": "吞库", "category": "鲜榴莲", "lat": 13.6332428, "lng": 100.5093501, "address": "85/383 Soi Pracha Uthit 79, Thung Khru, Bangkok 10140。", "directions": "85/383 Soi Pracha Uthit 79, Thung Khru, Bangkok 10140。 地图为79 巷道路区域线索，不是已核实店门口。", "description": "公开资料列出榴莲商家地址，需联系确认到店取货方式。", "source": "https://www.ryoiireview.com/restaurant/view/21256", "sourceName": "Ryoii 独立店铺资料", "checked": "2026-10-06", "status": "79 巷道路区域 · 营业待核实", "varieties": ["金枕"], "phone": "0926467288", "locationPrecision": "79 巷道路区域", "sourceDate": "来源未标注更新日期"}
];
function destination(p:Place){return p.navigationQuery||p.thai+' '+(p.address||'Bangkok');}
export function googleNavigation(p: Place) {return 'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(destination(p));}
export function appleNavigation(p: Place) {return 'https://maps.apple.com/?daddr='+encodeURIComponent(destination(p))+'&dirflg=w';}
export function distance(lat: number,lng: number,p: Place) { const r=Math.PI/180; const a=Math.sin((p.lat-lat)*r/2)**2+Math.cos(lat*r)*Math.cos(p.lat*r)*Math.sin((p.lng-lng)*r/2)**2; return 6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a)); }
