import {sqliteTable,text,integer,real,primaryKey,index} from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),name:text('name').notNull(),bio:text('bio').notNull().default(''),createdAt:integer('created_at').notNull()});
export const posts=sqliteTable('posts',{id:text('id').primaryKey(),userId:text('user_id').notNull(),placeId:text('place_id').notNull(),rating:integer('rating').notNull(),content:text('content').notNull(),visitDate:text('visit_date').notNull(),variety:text('variety').notNull().default('未确认'),texture:text('texture').notNull().default(''),sweetness:text('sweetness').notNull().default(''),aroma:text('aroma').notNull().default(''),price:real('price'),weight:real('weight'),basis:text('basis').notNull().default('未记录'),photos:text('photos').notNull().default('[]'),status:text('status').notNull().default('active'),createdAt:integer('created_at').notNull()},t=>[index('idx_posts_status_created').on(t.status,t.createdAt),index('idx_posts_place_status').on(t.placeId,t.status),index('idx_posts_user').on(t.userId)]);
export const comments=sqliteTable('comments',{id:text('id').primaryKey(),postId:text('post_id').notNull(),userId:text('user_id').notNull(),content:text('content').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_comments_post').on(t.postId)]);
export const likes=sqliteTable('likes',{userId:text('user_id').notNull(),postId:text('post_id').notNull()},t=>[primaryKey({columns:[t.userId,t.postId]}),index('idx_likes_post').on(t.postId)]);
export const favorites=sqliteTable('favorites',{userId:text('user_id').notNull(),placeId:text('place_id').notNull()},t=>[primaryKey({columns:[t.userId,t.placeId]})]);
export const submissions=sqliteTable('submissions',{id:text('id').primaryKey(),userId:text('user_id').notNull(),payload:text('payload').notNull(),status:text('status').notNull().default('pending'),createdAt:integer('created_at').notNull()},t=>[index('idx_submissions_status').on(t.status)]);
export const reports=sqliteTable('reports',{id:text('id').primaryKey(),userId:text('user_id').notNull(),target:text('target').notNull(),reason:text('reason').notNull(),status:text('status').notNull().default('pending'),createdAt:integer('created_at').notNull()});
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const uploads=sqliteTable('uploads',{id:text('id').primaryKey(),userId:text('user_id').notNull(),contentType:text('content_type').notNull(),createdAt:integer('created_at').notNull()});

export const rateLimits=sqliteTable('rate_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expiresAt:integer('expires_at').notNull()});
